language: ruby
cache: bundler
rvm:
- 2.2.0
sudo: false
notifications:
  slack:
    secure: lPIJLWqB2OsX4I4iVN7j+MG/Sp2Ztw03Lx11vKVi7u+aATo9UsGs2C8Av5aP8vIYnRycazYsD+Zr3z79UKOO8yXaGltWlp77bFjomiRn0F0CLjt5I1rj/pE/TG/MNHRJdod3NXTAlo59ObROiX45kjyeUWGPj000MYNlLbnEg1w=
